### ISSUE TITLE
Add allcontributors

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/CompNeuroCookBook#10]
@appukuttan-shailesh : I don't seem to have the permissions to add allcontributors to this repo. Could you please add it to this one and the softwareWG main repo too please?

https://allcontributors.org/docs/en/bot/installation

**Comment by appukuttan-shailesh** [comment]
@sanjayankur31 : I have added both you and Marcel as admin's for this repo. (Previously, I had done this only for the SoftwareWG repo).

Can you give it a go now and see if you have the required permissions?

**Comment by sanjayankur31** [comment]
Hrm, doesn't look like it. Something to do with org perms I think:

![image](https://github.com/OCNS/CompNeuroCookBook/assets/102575/6dd5f2c2-d0fa-4d13-a981-041b11d5619c)

**Comment by sanjayankur31** [comment]
Uh, that's crap. Let's see if all contributors works now:

@all-contributors add @appukuttan-shailesh for infra,maintenance,projectManagement

**Comment by sanjayankur31** [comment]
let's trying this again 

@all-contributors please add @appukuttan-shailesh for infra,maintenance,projectManagement
